version: '3.8'

services:
  backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./example-frontend
      dockerfile: Dockerfile
    ports:
      - 5050:5000